services:
  nexus_db:
    image: postgres:14
    container_name: nexus_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
    ports:
      - 5432:5432
    volumes:
      - ./config/docker/initdb:/docker-entrypoint-initdb.d
      - nexus_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - default

  # Nexus server - depends on database being healthy
  nexus_server:
    build:
      context: .
      dockerfile: Dockerfile.nexus
    container_name: nexus_server
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-false}
      - NEXUS_MINION_PORT=${NEXUS_MINION_PORT:-11972}
      - NEXUS_CONSOLE_PORT=${NEXUS_CONSOLE_PORT:-11973}
      - DBHOST=nexus_db
      - DBPORT=${DBPORT:-5432}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBNAME=${DBNAME}
    ports:
      - "${NEXUS_MINION_PORT:-11972}:${NEXUS_MINION_PORT:-11972}"
      - "${NEXUS_CONSOLE_PORT:-11973}:${NEXUS_CONSOLE_PORT:-11973}"
    depends_on:
      nexus_db:
        condition: service_healthy
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${NEXUS_MINION_PORT:-11972} && nc -z localhost ${NEXUS_CONSOLE_PORT:-11973} || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Minion client - depends on nexus server being healthy
  minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    container_name: minion
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=true
      - MINION_ID=${MINION_ID:-docker-minion}
      - NEXUS_SERVER=nexus_server
      - NEXUS_MINION_PORT=${NEXUS_MINION_PORT:-11972}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60}
      - INITIAL_RECONNECT_DELAY=${INITIAL_RECONNECT_DELAY:-1}
      - MAX_RECONNECT_DELAY=${MAX_RECONNECT_DELAY:-3600}
      - CONNECT_TIMEOUT=${CONNECT_TIMEOUT:-3}
    depends_on:
      nexus_server:
        condition: service_healthy
    networks:
      - default

  # Console client - depends on nexus server being healthy
  console:
    build:
      context: .
      dockerfile: Dockerfile.console
    container_name: minexus_console
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-false}
      - NEXUS_SERVER=nexus_server
      - NEXUS_CONSOLE_PORT=${NEXUS_CONSOLE_PORT:-11973}
      - CONNECT_TIMEOUT=${CONNECT_TIMEOUT:-3}
    depends_on:
      nexus_server:
        condition: service_healthy
    networks:
      - default
    stdin_open: true
    tty: true
    profiles:
      - console

volumes:
  nexus_db_data:
